# netlify.toml
[build]
  command = "npm run build"    # ya tera actual build command
  publish = "build"            # CRA default build folder

[[headers]]
  for = "/static/js/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=UTF-8"